### ISSUE TITLE
Is this in deckbox or InexF?

### ISSUE THREAD

**Issue by brightbold** [North101/mpc_project_helper#2]
To reproduce:
1. Choose Add item from the bottom of the Kanban board
2. Choose Add a draft
3. Add the draft then Convert to issue
4. You can now can choose mpc_project_helper instead of deckbox and it puts the issue in the Inexorable Fate project, but not the Inexorable Fate organization

**Comment by North101** [comment]
No idea. I haven't done anything with the kanban board

**Comment by brightbold** [comment]
Sorry I was just experimenting to see what was going on.
